armor_detector_tensorrt:
  ros__parameters:
    use_sim_time: false
    debug_mode: true
    target_color: 0
    use_sensor_data_qos: true

    detector:
      camera_name: 'front_industrial_camera'
      subscribe_compressed: false

      model_path: $(find-pkg-share armor_detector_tensorrt)/model/opt-1208-001.onnx
      device_type: 'AUTO'
      confidence_threshold: 0.25
      top_k: 128
      nms_threshold: 0.3